// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Lams IT Solutions
const SKIP_MAP = {
  homepage: new Set([
    "Breadcrumb Schema",
    "Content Freshness",
    "Content Depth",
    "Author & Expertise",
    "Source Attribution",
    "Answer Capsules",
    "Citation Worthiness",
    "Answer Density",
    "Question Headings",
    "Definition Clarity",
    "Sentence Complexity",
    "Content Readability",
    "HowTo Schema",
    "Speakable Schema",
    "AI Disclosure",
  ]),
  article: new Set([
    "Value Proposition",
    "CTA Effectiveness",
    "Social Proof",
    "CTA Above Fold",
    "CTA Copy Quality",
    "Trust Near CTAs",
    "Form Optimization",
    "Reviews & Ratings",
    "Contact Visibility",
    "Trust Signals",
    // New marketing checks — not applicable to articles
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Above-Fold Messaging",
    "Social Proof Signals",
  ]),
  product: new Set([
    "Answer Capsules",
    "Citation Worthiness",
    "Source Attribution",
    "Definition Clarity",
    "Question Headings",
    "Author & Expertise",
    "Content Freshness",
    "Content Readability",
    "Sentence Complexity",
    "Speakable Schema",
    "Value Proposition",
    "HowTo Schema",
    "AI Disclosure",
  ]),
  service: new Set([
    "Answer Capsules",
    "Citation Worthiness",
    "Source Attribution",
    "Definition Clarity",
    "Question Headings",
    "HowTo Schema",
    "AI Disclosure",
  ]),
  legal: new Set([
    // Marketing — not applicable to legal boilerplate
    "Value Proposition",
    "CTA Effectiveness",
    "CTA Above Fold",
    "CTA Copy Quality",
    "Trust Near CTAs",
    "Trust Signals",
    "Social Proof",
    "Reviews & Ratings",
    "Form Optimization",
    "Video Content",
    "Logo Detection",
    "Typography Quality",
    // New marketing checks
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Headline Formula Quality",
    "Above-Fold Messaging",
    "Social Proof Signals",
    // LLM — legal text is boilerplate, not content
    "Answer Capsules",
    "Citation Worthiness",
    "Answer Density",
    "Question Headings",
    "Definition Clarity",
    "Content Freshness",
    "Author & Expertise",
    "Source Attribution",
    "HowTo Schema",
    "Speakable Schema",
    "Content Readability",
    "Sentence Complexity",
    "Content Structure Consistency",
    // AI quality checks — not applicable to legal boilerplate
    "CTA Relevance",
    "Value Prop Clarity",
    "Brand Consistency",
    "Content-Audience Fit",
    // SEO — legal pages don't need rich results or social sharing
    "Open Graph Tags",
    "Content Depth",
    "Schema Completeness",
    "Breadcrumb Schema",
    "AI Content Quality",
    "AI Disclosure",
    "Schema Currency",
    "Privacy & Security",
    "Contact Visibility",
    "Review Schema Integrity",
  ]),
  utility: new Set([
    // Marketing — contact/about pages are not conversion pages
    "Value Proposition",
    "CTA Effectiveness",
    "CTA Above Fold",
    "CTA Copy Quality",
    "Trust Near CTAs",
    "Trust Signals",
    "Social Proof",
    "Reviews & Ratings",
    "Content Structure Consistency",
    "Video Content",
    // New marketing checks
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Headline Formula Quality",
    "Above-Fold Messaging",
    "Social Proof Signals",
    // AI quality checks — not applicable to utility pages
    "CTA Relevance",
    "Value Prop Clarity",
    "Brand Consistency",
    "Content-Audience Fit",
    // LLM — utility pages are not content pages
    "Answer Capsules",
    "Citation Worthiness",
    "Answer Density",
    "Question Headings",
    "Definition Clarity",
    "HowTo Schema",
    "Speakable Schema",
    "Content Freshness",
    "Content Readability",
    "Sentence Complexity",
    "AI Disclosure",
  ]),
  landing: new Set([
    // LLM — landing pages are conversion-focused, not content
    "Answer Capsules",
    "Citation Worthiness",
    "Source Attribution",
    "Content Freshness",
    "Author & Expertise",
    "HowTo Schema",
    "Definition Clarity",
    "Content Readability",
    "Sentence Complexity",
    "Question Headings",
    "Source Citations",
    "AI Disclosure",
  ]),
  faq: new Set([
    // Marketing — FAQ pages convert via answers, not CTAs
    "Value Proposition",
    "CTA Effectiveness",
    "CTA Above Fold",
    "CTA Copy Quality",
    "Trust Near CTAs",
    "Form Optimization",
    "Social Proof",
    "Reviews & Ratings",
    // New marketing checks (Headline Formula Quality runs on FAQ)
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Above-Fold Messaging",
    "Social Proof Signals",
    // LLM/SEO — FAQ format has many short answers
    "HowTo Schema",
    "Speakable Schema",
    "Content Depth",
  ]),
  auth: new Set([
    // Marketing — app pages, skip all except technical
    "Value Proposition",
    "CTA Effectiveness",
    "CTA Above Fold",
    "CTA Copy Quality",
    "Trust Near CTAs",
    "Form Optimization",
    "Social Proof",
    "Reviews & Ratings",
    "Trust Signals",
    "Video Content",
    "Logo Detection",
    "Typography Quality",
    "Contact Visibility",
    "Content Structure Consistency",
    "Privacy & Security",
    // New marketing checks
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Headline Formula Quality",
    "Above-Fold Messaging",
    "Social Proof Signals",
    // AI quality checks — not applicable to auth pages
    "CTA Relevance",
    "Value Prop Clarity",
    "Brand Consistency",
    "Content-Audience Fit",
    // All LLM checks
    "Answer Capsules",
    "Citation Worthiness",
    "Answer Density",
    "Question Headings",
    "Definition Clarity",
    "Content Freshness",
    "Author & Expertise",
    "Source Attribution",
    "HowTo Schema",
    "Speakable Schema",
    "Content Readability",
    "Sentence Complexity",
    // SEO content checks
    "Content Depth",
    "Schema Completeness",
    "AI Content Quality",
    "AI Disclosure",
    "Internal Linking",
    "Breadcrumb Schema",
    "Open Graph Tags",
    "Schema Currency",
    "Review Schema Integrity",
  ]),
  gallery: new Set([
    // Image-heavy pages — low text content is expected
    "Content Depth",
    "Content Readability",
    "Sentence Complexity",
    "Answer Capsules",
    "Answer Density",
    "Citation Worthiness",
    "Question Headings",
    "Definition Clarity",
    "AI Content Quality",
    "AI Disclosure",
    "Content Structure Consistency",
    // New marketing checks
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Headline Formula Quality",
    "Above-Fold Messaging",
    "Social Proof Signals",
  ]),
  support: new Set([
    // Marketing — support/docs pages help users, not convert them
    "Value Proposition",
    "CTA Effectiveness",
    "CTA Above Fold",
    "CTA Copy Quality",
    "Trust Near CTAs",
    "Social Proof",
    "Reviews & Ratings",
    "Form Optimization",
    "Trust Signals",
    "Video Content",
    "Content Structure Consistency",
    // New marketing checks
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Headline Formula Quality",
    "Above-Fold Messaging",
    "Social Proof Signals",
    // LLM — keep most LLM checks (support content is great for AI citation)
    "Speakable Schema",
    "AI Disclosure",
  ]),
  generic: new Set([
    // New marketing checks — generic pages have unknown intent
    "Benefit vs. Feature Language",
    "Urgency & Scarcity",
    "Emotional Trigger Words",
    "Headline Formula Quality",
    "Above-Fold Messaging",
    "Social Proof Signals",
  ]),
};

function shouldSkipCheck(pageType, checkLabel) {
  return SKIP_MAP[pageType]?.has(checkLabel) || false;
}

module.exports = { SKIP_MAP, shouldSkipCheck };
